name: voting_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  animated_splash_screen: ^1.3.0
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  local_auth_darwin: ^1.4.1
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.12.0
  syncfusion_flutter_charts: ^20.4.44
  firebase_admin: ^0.3.0
  email_validator: ^3.0.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
     - assets/voting_logo.png