// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_o3C8Powwnh_xgLaPUE5cVsz7Eqqxsec',
    appId: '1:482734270160:web:9d4a84816e990811fbe0d5',
    messagingSenderId: '482734270160',
    projectId: 'voting-system-c5b06',
    authDomain: 'voting-system-c5b06.firebaseapp.com',
    storageBucket: 'voting-system-c5b06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTrLELw2-WZNG5kJVPtbaVRSjEKs1yRAQ',
    appId: '1:482734270160:android:4880f16eb09ef9dffbe0d5',
    messagingSenderId: '482734270160',
    projectId: 'voting-system-c5b06',
    storageBucket: 'voting-system-c5b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8L0cBkOd4Oel1sr8wVg2jcbzvn3azZ-4',
    appId: '1:482734270160:ios:8e4f2c26b89c4223fbe0d5',
    messagingSenderId: '482734270160',
    projectId: 'voting-system-c5b06',
    storageBucket: 'voting-system-c5b06.appspot.com',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8L0cBkOd4Oel1sr8wVg2jcbzvn3azZ-4',
    appId: '1:482734270160:ios:8e4f2c26b89c4223fbe0d5',
    messagingSenderId: '482734270160',
    projectId: 'voting-system-c5b06',
    storageBucket: 'voting-system-c5b06.appspot.com',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_o3C8Powwnh_xgLaPUE5cVsz7Eqqxsec',
    appId: '1:482734270160:web:7b788a90e997d765fbe0d5',
    messagingSenderId: '482734270160',
    projectId: 'voting-system-c5b06',
    authDomain: 'voting-system-c5b06.firebaseapp.com',
    storageBucket: 'voting-system-c5b06.appspot.com',
  );
}
